language: node_js

version: 
  - v10.15.1

cache: 
  - node

install:
  - npm install

before_deploy:
  - echo "ready to deploy"

deploy: 
  provider: 
    - heroku
  env: 
    - APP_NAME=webpack-104-university
  apiKey: 
    - ${HEROKU_API_KEY}
  app: 
    - ${APP_NAME}
  skip_cleanup: true

# jobs:
#   include:
#     - stage: "build"               
#       name: "build project"        
#       script: npm run build
#     - stage: "start-server"
#       name: "start-server"
#       env: 
#         - PORT=80
#       script: npm run start




