language: node_js

node_js: 
  - "10"

branches:
  only:
    - master

cache: 
  - node

install:
  - npm install

before_deploy:
  - echo "ready to deploy"

jobs: 
  include:
    - stage: lint test
      if: |
       branch = master AND \
       type = push
      script: "npm run test"
    - stage: deploy
      deploy: 
        provider: 
          - heroku
        api_key: ${HEROKU_API_KEY}
        app: 
          master: webpack-104-university
        skip_cleanup: true





